// create cities collection

db = new Mongo().getDB("rndbase")

db.createCollection("cities", {
    validator: {
	$jsonSchema: {
	    bsonType: "object",
	    required: ["name", "region"],
	    properties: {
		name: {
		    bsonType: "string",
		    description: "internal city name"
		},
		region: {
		    bsonType: "string",
		    description: "internal region name"
		},
		"en.name": {
		    bsonType: "string",
		    description: "name of the city in British English"
		},
	    }
	}
    }
})

// create indexes needed in the collection
db.cities.createIndex({'name': 1}, {unique: true})
db.cities.createIndex({'region': 1})

// insert initial data
db.cities.insertMany([
    { name: 'dublin',
      en: {name: 'Dublin'},
      region: 'north-west'},
    { name: 'glasgow',
      en: {name: 'Glasgow'},
      region: 'north-west'},
    { name: 'cardiff',
      en: {name: 'Cardiff'},
      region: 'north-west'},
    { name: 'london',
      en: {name: 'London'},
      region: 'north-west'},
    { name: 'manchester',
      en: {name: 'Manchester'},
      region: 'north-west'},
    { name: 'madrid',
      en: {name: 'Madrid'},
      region: 'south-west'},
    { name: 'barcelona',
      en: {name: 'Barcelona'},
      region: 'south-west'},
    { name: 'porto',
      en: {name: 'Porto'},
      region: 'south-west'},
    { name: 'malaga',
      en: {name: 'Malaga'},
      region: 'south-west'},
    { name: 'lisbon',
      en: {name: 'Lisbon'},
      region: 'south-west'},
    { name: 'paris',
      en: {name: 'Paris'},
      region: 'west'},
    { name: 'brussel',
      en: {name: 'Brussel'},
      region: 'west'},
    { name: 'bordeaux',
      en: {name: 'Bordeaux'},
      region: 'west'},
    { name: 'lyon',
      en: {name: 'Lyon'},
      region: 'west'},
    { name: 'marseille',
      en: {name: 'Marseille'},
      region: 'west'},
    { name: 'amsterdam',
      en: {name: 'Amsterdam'},
      region: 'central'},
    { name: 'berlin',
      en: {name: 'Berlin'},
      region: 'central'},
    { name: 'hamburg',
      en: {name: 'Hamburg'},
      region: 'central'},
    { name: 'cologne',
      en: {name: 'Cologne'},
      region: 'central'},
    { name: 'munich',
      en: {name: 'Munich'},
      region: 'central'},
    { name: 'copenhagen',
      en: {name: 'Copenhagen'},
      region: 'north'},
    { name: 'gothenborg',
      en: {name: 'Gothenborg'},
      region: 'north'},
    { name: 'oslo',
      en: {name: 'Oslo'},
      region: 'north'},
    { name: 'stockholm',
      en: {name: 'Stockholm'},
      region: 'north'},
    { name: 'helsinki',
      en: {name: 'Helsinki'},
      region: 'north'},
    { name: 'zurich',
      en: {name: 'Zurich'},
      region: 'south'},
    { name: 'milan',
      en: {name: 'Milan'},
      region: 'south'},
    { name: 'rome',
      en: {name: 'Rome'},
      region: 'south'},
    { name: 'naples',
      en: {name: 'Naples'},
      region: 'south'},
    { name: 'palermo',
      en: {name: 'Palermo'},
      region: 'south'},
    { name: 'zagreb',
      en: {name: 'Zagreb'},
      region: 'south-southeast'},
    { name: 'sarajevo',
      en: {name: 'Sarajevo'},
      region: 'south-southeast'},
    { name: 'vienna',
      en: {name: 'Vienna'},
      region: 'south-southeast'},
    { name: 'budapest',
      en: {name: 'Budapest'},
      region: 'south-southeast'},
    { name: 'Belgrade',
      en: {name: 'belgrade'},
      region: 'south-southeast'},
    { name: 'chisinau',
      en: {name: 'Chisinau'},
      region: 'south-east'},
    { name: 'istanbul',
      en: {name: 'Istanbul'},
      region: 'south-east'},
    { name: 'sofia',
      en: {name: 'Sofia'},
      region: 'south-east'},
    { name: 'athens',
      en: {name: 'Athens'},
      region: 'south-east'},
    { name: 'bucharest',
      en: {name: 'Bucharest'},
      region: 'south-east'},
    { name: 'donetsk',
      en: {name: 'Donetsk'},
      region: 'east'},
    { name: 'moskow',
      en: {name: 'Moskow'},
      region: 'east'},
    { name: 'kiev',
      en: {name: 'Kiev'},
      region: 'east'},
    { name: 'minsk',
      en: {name: 'Minsk'},
      region: 'east'},
    { name: 'st petersburg',
      en: {name: 'St Petersburg'},
      region: 'east'},
    { name: 'vilnius',
      en: {name: 'Vilnius'},
      region: 'north-east'},
    { name: 'riga',
      en: {name: 'Riga'},
      region: 'north-east'},
    { name: 'warsaw',
      en: {name: 'Warsaw'},
      region: 'north-east'},
    { name: 'gdansk',
      en: {name: 'Gdansk'},
      region: 'north-east'},
    { name: 'prague',
      en: {name: 'Prague'},
      region: 'north-east'}])






