version: '3.6'
services:
  db:
    image: mongo:4
    ports:
      - "27017:27017"
  web:
    image: rndbase/flask
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ../web
        target: /app
